Default: &defaults
  database: homebase.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Test:
  database: homebase_test.sqlite3
  <<: *defaults

Staging:
  database: homebase_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: homebase_production.sqlite3
  poolsize: 100
  <<: *defaults